### ISSUE TITLE
How long does it take to generate a 3D model, how much graphics memory is required, and can it run on VRAM of 12GB or less? Can it run in Colab

### ISSUE THREAD

**Issue by libai-lab** [YuQiao0303/PointDreamer#1]
How long does it take to generate a 3D model, how much graphics memory is required, and can it run on VRAM of 12GB or less? Can it run in Colab

**Comment by YuQiao0303** [comment]
Hi! 

**Inference time**: The inference time depends on your hardware. We tried on a A100 GPU (~60 s per shape), and a 3090 GPU (~100s per shape). On Colab it may be slower (about 200 s)

**Graphic memory**: It seems that it will require 24GB to run the code, although most of the time only less than 10GB is used. We may check the code later to see why the graphic memory may rise to about 23GB sometimes.

**Colab**: We just provide a Colab demo: https://colab.research.google.com/drive/1gvc2OEotw43eVjwk1WQZMPYf1iVT3SXW?usp=sharing .  Feel free to check it out! Or you can try the newly uploaded .ipynb file.
